<?php
/**
 * Include the configuration submenu as a hidden block at the end of the page and init a modal to be opened when
 * clicking on the "Configuration" link.
 */

/** @var \Magento\Config\Block\System\Config\Tabs $submenu */
$submenu = $this->getChildHtml('config.submenu'); 
?>
<div class="config-submenu" style="display: none;" data-mage-init='{"storeConfigSubmenu":{}}'>
    <?= $submenu; ?>
</div>